package com.example.voxel_review.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF615690)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE7DEFF)
val onPrimaryContainerLight = Color(0xFF493E76)
val secondaryLight = Color(0xFF006874)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF9EEFFD)
val onSecondaryContainerLight = Color(0xFF004F58)
val tertiaryLight = Color(0xFF6D538B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFEFDBFF)
val onTertiaryContainerLight = Color(0xFF543B72)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFDF8FF)
val onBackgroundLight = Color(0xFFFFD700)
val surfaceLight = Color(0xFFFDF8FF)
val onSurfaceLight = Color(0xFF1C1B20)
val surfaceVariantLight = Color(0xFFE6E0EC)
val onSurfaceVariantLight = Color(0xFF48454E)
val outlineLight = Color(0xFF79757F)
val outlineVariantLight = Color(0xFFC9C4CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF312F36)
val inverseOnSurfaceLight = Color(0xFFF4EFF7)
val inversePrimaryLight = Color(0xFFCBBEFF)
val surfaceDimLight = Color(0xFFDDD8E0)
val surfaceBrightLight = Color(0xFFFDF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F2FA)
val surfaceContainerLight = Color(0xFFF1ECF4)
val surfaceContainerHighLight = Color(0xFFECE6EE)
val surfaceContainerHighestLight = Color(0xFFE6E1E9)


val primaryDark = Color(0xFF2A2254)
val onPrimaryDark = Color(0xFF2A2254)
val primaryContainerDark = Color(0xFF040C15)
val onPrimaryContainerDark = Color(0xFF8F00FF)
val secondaryDark = Color(0xFF00F0FF)
val onSecondaryDark = Color(0xFF00363D)
val secondaryContainerDark = Color(0xFF004F58)
val onSecondaryContainerDark = Color(0xFF9EEFFD)
val tertiaryDark = Color(0xFFFF2E93)
val onTertiaryDark = Color(0xFF3D2459)
val tertiaryContainerDark = Color(0xFF543B72)
val onTertiaryContainerDark = Color(0xFFEFDBFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F0D1F)
val onBackgroundDark = Color(0xFFFFD700)
val surfaceDark = Color(0xFF000000)
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0xFFA09EBC)
val onSurfaceVariantDark = Color(0xFFC9C4CF)
val outlineDark = Color(0xFF938F99)
val outlineVariantDark = Color(0xFF48454E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E1E9)
val inverseOnSurfaceDark = Color(0xFF312F36)
val inversePrimaryDark = Color(0xFF615690)
val surfaceDimDark = Color(0xFF191430)
val surfaceBrightDark = Color(0xFF3A383E)
val surfaceContainerLowestDark = Color(0xFF0F0D13)
val surfaceContainerLowDark = Color(0xFF1C1B20)
val surfaceContainerDark = Color(0xFF201F24)
val surfaceContainerHighDark = Color(0xFF2B292F)
val surfaceContainerHighestDark = Color(0xFF36343A)

// Colores principales
val VoxelPrimary = Color(0xFF00F0FF)
val VoxelSecondary = Color(0xFFFF2E93)
val VoxelAccentPurple = Color(0xFF8F00FF)
val VoxelAccentYellow = Color(0xFFFFD700)

// Fondos y superficies
val VoxelBackground = Color(0xFF0F0D1F)
val VoxelSurface = Color(0xFF191430)
val VoxelSurfaceVariant = Color(0xFF2A2254)
val VoxelBackgroundDark = Color(0xFF040C15)

// Bordes
val VoxelBorder = Color(0xFF2E2B5F)

// Texto
val VoxelTextPrimary = Color(0xFFFFFFFF)
val VoxelTextSecondary = Color(0xFFA09EBC)

// Colores básicos
val White = Color(0xFFFFFFFF)
val Black = Color(0xFF000000)


val VoxelGameBlue = Color(0xFF1A3B66)
val VoxelGameOrange = Color(0xFF9E471A)